USE [master]
GO

/****** Object:  Database [chat]    Script Date: 2018-06-13 21:37:45 ******/
CREATE DATABASE [chat]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'chat', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\chat.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'chat_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\chat_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [chat] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [chat].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [chat] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [chat] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [chat] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [chat] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [chat] SET ARITHABORT OFF 
GO

ALTER DATABASE [chat] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [chat] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [chat] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [chat] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [chat] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [chat] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [chat] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [chat] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [chat] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [chat] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [chat] SET  DISABLE_BROKER 
GO

ALTER DATABASE [chat] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [chat] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [chat] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [chat] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [chat] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [chat] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [chat] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [chat] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [chat] SET  MULTI_USER 
GO

ALTER DATABASE [chat] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [chat] SET DB_CHAINING OFF 
GO

ALTER DATABASE [chat] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [chat] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [chat] SET  READ_WRITE 
GO

